"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { X, CaretLeft, CaretRight } from "@phosphor-icons/react";

const INDUSTRIES = [
  { id: "solar", label: "Solar", pages: 12, pad: true },
  { id: "solar2", label: "Solar & Electrical", pages: 17, pad: true },
  { id: "roofing2", label: "Roofing", pages: 3, pad: false },
  { id: "cleaning", label: "Cleaning", pages: 9, pad: false },
] as const;

function getImages(industry: (typeof INDUSTRIES)[number]) {
  return Array.from({ length: industry.pages }, (_, i) => {
    const n = i + 1;
    const page = industry.pad ? String(n).padStart(2, "0") : String(n);
    return `/showcase/${industry.id}/page-${page}.webp`;
  });
}

export default function Showcase() {
  const [activeIdx, setActiveIdx] = useState(0);
  const [lightboxIdx, setLightboxIdx] = useState<number | null>(null);
  const [fadeKey, setFadeKey] = useState(0);
  const stripRef = useRef<HTMLDivElement>(null);
  const mobileRef = useRef<HTMLDivElement>(null);
  const raf = useRef<number | null>(null);
  const paused = useRef(false);
  const autoSpeed = useRef(0.5);

  // Touch tracking for lightbox swipe
  const touchStart = useRef<{ x: number; y: number } | null>(null);

  const industry = INDUSTRIES[activeIdx];
  const images = getImages(industry);

  // Switch industry with fade
  const switchIndustry = (idx: number) => {
    if (idx === activeIdx) return;
    setActiveIdx(idx);
    setFadeKey((k) => k + 1);
  };

  // Reset strip scroll on tab change
  useEffect(() => {
    if (stripRef.current) stripRef.current.scrollLeft = 0;
    if (mobileRef.current) mobileRef.current.scrollLeft = 0;
  }, [activeIdx]);

  // Auto-scroll loop — pauses on hover (desktop only)
  const tick = useCallback(() => {
    const el = stripRef.current;
    if (el && !paused.current) {
      const maxScroll = el.scrollWidth - el.clientWidth;
      if (el.scrollLeft >= maxScroll) {
        el.scrollLeft = 0;
      } else {
        el.scrollLeft += autoSpeed.current;
      }
    }
    raf.current = requestAnimationFrame(tick);
  }, []);

  useEffect(() => {
    raf.current = requestAnimationFrame(tick);
    return () => {
      if (raf.current) cancelAnimationFrame(raf.current);
    };
  }, [tick]);

  // Lightbox keyboard nav
  useEffect(() => {
    if (lightboxIdx === null) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") setLightboxIdx(null);
      if (e.key === "ArrowRight") setLightboxIdx((i) => i !== null ? Math.min(i + 1, images.length - 1) : null);
      if (e.key === "ArrowLeft") setLightboxIdx((i) => i !== null ? Math.max(i - 1, 0) : null);
    };
    window.addEventListener("keydown", handler);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", handler);
      document.body.style.overflow = "";
    };
  }, [lightboxIdx, images.length]);

  // Lightbox touch swipe handlers
  const onTouchStart = (e: React.TouchEvent) => {
    touchStart.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
  };

  const onTouchEnd = (e: React.TouchEvent) => {
    if (!touchStart.current || lightboxIdx === null) return;
    const dx = e.changedTouches[0].clientX - touchStart.current.x;
    const dy = e.changedTouches[0].clientY - touchStart.current.y;
    // Only count horizontal swipes (not vertical scrolls)
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) {
      if (dx < 0 && lightboxIdx < images.length - 1) {
        setLightboxIdx(lightboxIdx + 1);
      } else if (dx > 0 && lightboxIdx > 0) {
        setLightboxIdx(lightboxIdx - 1);
      }
    }
    touchStart.current = null;
  };

  return (
    <section className="pt-16 sm:pt-24 pb-16 sm:pb-24 overflow-hidden border-t border-white/[0.04]" style={{ background: "#08080c" }}>
      {/* Header */}
      <div className="text-center mb-6 sm:mb-12 px-4">
        <h2 className="text-2xl sm:text-3xl lg:text-5xl font-extrabold tracking-tight text-white mb-3 sm:mb-4 font-[family-name:var(--font-jakarta)]">
          This is what your clients receive.
        </h2>
        <p className="text-sm sm:text-base lg:text-lg text-white/40 max-w-lg mx-auto">
          Real quotes, generated by real customers, in under 30 seconds each.
        </p>
      </div>

      {/* Industry tabs — horizontally scrollable on mobile */}
      <div className="mx-auto max-w-[1440px] px-0 sm:px-6 lg:px-8 xl:px-12 mb-6 sm:mb-10">
        <div className="flex items-center sm:justify-center gap-2 sm:gap-3 overflow-x-auto scrollbar-hide px-4 sm:px-0 sm:flex-wrap">
          {INDUSTRIES.map((ind, i) => (
            <button
              key={ind.id}
              onClick={() => switchIndustry(i)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 whitespace-nowrap flex-shrink-0 ${
                i === activeIdx
                  ? "bg-white/[0.12] text-white border border-white/[0.2] shadow-lg shadow-white/[0.03]"
                  : "text-white/40 hover:text-white/70 border border-transparent hover:border-white/[0.08]"
              }`}
            >
              {ind.label}
              <span className="ml-2 text-xs opacity-50">{ind.pages}pg</span>
            </button>
          ))}
        </div>
      </div>

      {/* Desktop auto-scroll strip */}
      <div className="relative hidden md:block">
        {/* Edge fades */}
        <div className="pointer-events-none absolute left-0 top-0 bottom-0 w-40 z-10 bg-gradient-to-r from-[#08080c] via-[#08080c]/80 to-transparent" />
        <div className="pointer-events-none absolute right-0 top-0 bottom-0 w-40 z-10 bg-gradient-to-l from-[#08080c] via-[#08080c]/80 to-transparent" />

        <div
          ref={stripRef}
          key={fadeKey}
          className="flex gap-5 overflow-x-auto scrollbar-hide px-20 py-6 showcase-fade-in"
          style={{ scrollBehavior: "auto" }}
          onMouseEnter={() => { paused.current = true; }}
          onMouseLeave={() => { paused.current = false; }}
        >
          {images.map((src, i) => (
            <button
              key={`${industry.id}-${i}`}
              onClick={() => setLightboxIdx(i)}
              className="group flex-shrink-0 rounded-xl overflow-hidden border border-white/[0.08] bg-white/[0.02] transition-all duration-300 hover:border-white/[0.2] hover:shadow-[0_0_40px_rgba(59,130,246,0.12)] hover:scale-[1.04] hover:-translate-y-1 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/50 relative"
              style={{
                width: "clamp(220px, 22vw, 320px)",
                aspectRatio: "0.707",
                animationDelay: `${i * 40}ms`,
              }}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={src}
                alt={`${industry.label} page ${i + 1}`}
                className="w-full h-full object-contain block transition-all duration-300 group-hover:brightness-110"
                style={{ filter: "blur(6px)", transform: "scale(1.08)" }}
                loading="eager"
                draggable={false}
              />
              {/* Hover overlay */}
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-black/20 backdrop-blur-[1px]">
                <span className="px-3 py-1.5 rounded-lg bg-white/10 backdrop-blur-md text-white text-xs font-medium border border-white/20">
                  Page {i + 1}
                </span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Mobile swipe strip */}
      <div className="relative md:hidden">
        <div className="pointer-events-none absolute left-0 top-0 bottom-0 w-12 z-10 bg-gradient-to-r from-[#08080c] to-transparent" />
        <div className="pointer-events-none absolute right-0 top-0 bottom-0 w-12 z-10 bg-gradient-to-l from-[#08080c] to-transparent" />

        <div
          ref={mobileRef}
          key={fadeKey}
          className="flex gap-3 overflow-x-auto scrollbar-hide px-6 py-4 snap-x snap-mandatory showcase-fade-in"
        >
          {images.map((src, i) => (
            <button
              key={`${industry.id}-${i}`}
              onClick={() => setLightboxIdx(i)}
              className="flex-shrink-0 snap-center rounded-lg overflow-hidden border border-white/[0.08] shadow-xl shadow-black/30 bg-white/[0.02] active:scale-95 transition-transform focus:outline-none relative"
              style={{ width: "65vw", maxWidth: "280px", aspectRatio: "0.707" }}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={src}
                alt={`${industry.label} page ${i + 1}`}
                className="w-full h-full object-contain block"
                style={{ filter: "blur(6px)", transform: "scale(1.08)" }}
                loading="eager"
                draggable={false}
              />
              {/* Page label */}
              <div className="absolute bottom-2 left-1/2 -translate-x-1/2 px-2 py-0.5 rounded-md bg-black/50 text-white/60 text-[10px] font-medium">
                {i + 1} / {images.length}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Hint text */}
      <div className="text-center mt-4 px-4">
        <p className="text-xs text-white/25">
          <span className="hidden sm:inline">Click any page to preview</span>
          <span className="sm:hidden">Tap to preview &middot; Swipe to browse</span>
        </p>
      </div>

      {/* Lightbox */}
      {lightboxIdx !== null && (
        <div
          className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/80 backdrop-blur-md animate-[fadeIn_200ms_ease-out]"
          onClick={() => setLightboxIdx(null)}
          onTouchStart={onTouchStart}
          onTouchEnd={onTouchEnd}
        >
          {/* Close — larger hit target on mobile */}
          <button
            onClick={() => setLightboxIdx(null)}
            className="absolute top-4 right-4 sm:top-6 sm:right-6 p-3 sm:p-2 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors z-10"
          >
            <X weight="duotone" className="w-5 h-5" />
          </button>

          {/* Desktop nav arrows — hidden on mobile (swipe instead) */}
          {lightboxIdx > 0 && (
            <button
              onClick={(e) => { e.stopPropagation(); setLightboxIdx(lightboxIdx - 1); }}
              className="hidden sm:block absolute left-4 sm:left-8 p-3 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors z-10"
            >
              <CaretLeft weight="duotone" className="w-6 h-6" />
            </button>
          )}
          {lightboxIdx < images.length - 1 && (
            <button
              onClick={(e) => { e.stopPropagation(); setLightboxIdx(lightboxIdx + 1); }}
              className="hidden sm:block absolute right-4 sm:right-8 p-3 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors z-10"
            >
              <CaretRight weight="duotone" className="w-6 h-6" />
            </button>
          )}

          {/* Image */}
          <div
            className="relative max-h-[75vh] sm:max-h-[85vh] max-w-[92vw] sm:max-w-[600px] animate-[scaleIn_200ms_ease-out]"
            onClick={(e) => e.stopPropagation()}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              key={lightboxIdx}
              src={images[lightboxIdx]}
              alt={`${industry.label} page ${lightboxIdx + 1}`}
              className="w-full h-full object-contain rounded-xl border border-white/[0.1] shadow-2xl"
              style={{ filter: "blur(6px)", transform: "scale(1.03)" }}
              draggable={false}
            />
          </div>

          {/* Bottom bar — page indicator + mobile nav arrows */}
          <div
            className="flex items-center justify-center gap-4 mt-4"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => lightboxIdx > 0 && setLightboxIdx(lightboxIdx - 1)}
              className={`sm:hidden p-2.5 rounded-full transition-colors ${
                lightboxIdx > 0
                  ? "bg-white/10 text-white active:bg-white/20"
                  : "bg-white/5 text-white/20"
              }`}
              disabled={lightboxIdx === 0}
            >
              <CaretLeft weight="bold" className="w-5 h-5" />
            </button>

            <div className="px-4 py-2 rounded-full bg-black/60 backdrop-blur-md text-white text-sm font-medium border border-white/10">
              {lightboxIdx + 1} / {images.length}
            </div>

            <button
              onClick={() => lightboxIdx < images.length - 1 && setLightboxIdx(lightboxIdx + 1)}
              className={`sm:hidden p-2.5 rounded-full transition-colors ${
                lightboxIdx < images.length - 1
                  ? "bg-white/10 text-white active:bg-white/20"
                  : "bg-white/5 text-white/20"
              }`}
              disabled={lightboxIdx === images.length - 1}
            >
              <CaretRight weight="bold" className="w-5 h-5" />
            </button>
          </div>

          {/* Swipe hint on mobile */}
          <p className="sm:hidden text-white/25 text-xs mt-3">Swipe to navigate</p>
        </div>
      )}
    </section>
  );
}
